### ISSUE TITLE
execute converts Integers to unsigned regardless of column type

### ISSUE THREAD

**Issue by KiitoX** [mariadb-corporation/mariadb-connector-python#14]
cursor.execute does not allow negative integers as parameters, as it tries to convert all integers to unsigned int even when a column is not set to unsigned, which in turn results in an OverflowError.

It seems this is happening irregardles of paramstyle

I feel this must be a major oversight since it means that insertion of negative values is just not possible

I am using:
Arch Linux 5.6.15
python 3.8.3
python-mariadb 0.9.59
mariadb 10.4.13

**Comment by 9EOR9** [comment]
Regression - fixed in rev. 190ea4eca9257a7711a93bbbe71a0149e8a9e602
